bash resume_test_grid.bash 20111
bash resume_test_grid.bash 20112
bash resume_test_grid.bash 20121
bash resume_test_grid.bash 20122
bash resume_test_grid.bash 20211
bash resume_test_grid.bash 20212
bash resume_test_grid.bash 20221
bash resume_test_grid.bash 20222
bash resume_test_grid.bash 20311
bash resume_test_grid.bash 20321
bash resume_test_grid.bash 20511
bash resume_test_grid.bash 20521
bash resume_test_grid.bash 20411
bash resume_test_grid.bash 20421
bash resume_test_grid.bash 20611
bash resume_test_grid.bash 20621
bash resume_test_grid.bash 20711
bash resume_test_grid.bash 20721
bash resume_test_grid.bash 30111
bash resume_test_grid.bash 30121
bash resume_test_grid.bash 30211
bash resume_test_grid.bash 30213
bash resume_test_grid.bash 30221
bash resume_test_grid.bash 30222
bash resume_test_grid.bash 30223
bash resume_test_grid.bash 30311
bash resume_test_grid.bash 30321
bash resume_test_grid.bash 30411
bash resume_test_grid.bash 30421
bash resume_test_grid.bash 30511
bash resume_test_grid.bash 30521
bash resume_test_grid.bash 40111
bash resume_test_grid.bash 40112
bash resume_test_grid.bash 40121
bash resume_test_grid.bash 40122
bash resume_test_grid.bash 40211
bash resume_test_grid.bash 40212
bash resume_test_grid.bash 40221
bash resume_test_grid.bash 40222
bash resume_test_grid.bash 40311
bash resume_test_grid.bash 40312
bash resume_test_grid.bash 40322
bash resume_test_grid.bash 50111
bash resume_test_grid.bash 50112
bash resume_test_grid.bash 50121
bash resume_test_grid.bash 50122
bash resume_test_grid.bash 50211
bash resume_test_grid.bash 50212
bash resume_test_grid.bash 50221
bash resume_test_grid.bash 50222
bash resume_test_grid.bash 50511
bash resume_test_grid.bash 50512
bash resume_test_grid.bash 50521
bash resume_test_grid.bash 50522
bash resume_test_grid.bash 50311
bash resume_test_grid.bash 50321
bash resume_test_grid.bash 50411
bash resume_test_grid.bash 50421
bash resume_test.bash -s 20111 -u 200
bash resume_test.bash -s 20112 -u 200
bash resume_test.bash -s 20121 -u 200
bash resume_test.bash -s 20122 -u 200
bash resume_test.bash -s 20211 -u 200
bash resume_test.bash -s 20212 -u 200
bash resume_test.bash -s 20221 -u 200
bash resume_test.bash -s 20222 -u 200
bash resume_test.bash -s 20311 -u 200
bash resume_test.bash -s 20321 -u 200
bash resume_test.bash -s 20511 -u 200
bash resume_test.bash -s 20521 -u 200
bash resume_test.bash -s 20411 -u 200
bash resume_test.bash -s 20421 -u 200
bash resume_test.bash -s 20611 -u 200
bash resume_test.bash -s 20621 -u 200
bash resume_test.bash -s 20711 -u 200
bash resume_test.bash -s 20721 -u 200
bash resume_test.bash -s 30111 -u 200
bash resume_test.bash -s 30121 -u 200
bash resume_test.bash -s 30211 -u 200
bash resume_test.bash -s 30213 -u 200
bash resume_test.bash -s 30221 -u 200
bash resume_test.bash -s 30222 -u 200
bash resume_test.bash -s 30223 -u 200
bash resume_test.bash -s 30311 -u 200
bash resume_test.bash -s 30321 -u 200
bash resume_test.bash -s 30411 -u 200
bash resume_test.bash -s 30421 -u 200
bash resume_test.bash -s 30511 -u 200
bash resume_test.bash -s 30521 -u 200
bash resume_test.bash -s 40111 -u 200
bash resume_test.bash -s 40112 -u 200
bash resume_test.bash -s 40121 -u 200
bash resume_test.bash -s 40122 -u 200
bash resume_test.bash -s 40211 -u 200
bash resume_test.bash -s 40212 -u 200
bash resume_test.bash -s 40221 -u 200
bash resume_test.bash -s 40222 -u 200
bash resume_test.bash -s 40311 -u 200
bash resume_test.bash -s 40312 -u 200
bash resume_test.bash -s 40322 -u 200
bash resume_test.bash -s 50111 -u 200
bash resume_test.bash -s 50112 -u 200
bash resume_test.bash -s 50121 -u 200
bash resume_test.bash -s 50122 -u 200
bash resume_test.bash -s 50211 -u 200
bash resume_test.bash -s 50212 -u 200
bash resume_test.bash -s 50221 -u 200
bash resume_test.bash -s 50222 -u 200
bash resume_test.bash -s 50511 -u 200
bash resume_test.bash -s 50512 -u 200
bash resume_test.bash -s 50521 -u 200
bash resume_test.bash -s 50522 -u 200
bash resume_test.bash -s 50311 -u 200
bash resume_test.bash -s 50321 -u 200
bash resume_test.bash -s 50411 -u 200
bash resume_test.bash -s 50421 -u 200
